import { Link } from "react-router-dom";
import { ArrowRight, Check, FileText, ShieldCheck } from "lucide-react";
import Button from "../../components/common/Button.jsx";
import PictureStimulus from "../../components/assessment/PictureStimulus.jsx";
import styles from "./Landing.module.css";
const languages = [['English', 'English'], ['Hindi', 'हिन्दी'], ['Marathi', 'मराठी'], ['Tamil', 'தமிழ்'], ['Bengali', 'বাংলা'], ['Telugu', 'తెలుగు'], ['Urdu', 'اُردُو'], ['Kannada', 'ಕನ್ನಡ']];
export default function Landing() {
    return <div className={styles.page}>
        <section className={styles.hero}><div className="container"><div className={styles.heroGrid}><div><p className={styles.eyebrow}>Multilingual cognitive assessment</p><h1>Speech, recorded clearly.<br /><span>Reviewed over time.</span></h1><p className={styles.lead}>Memora uses structured picture-description tasks to capture speech and language for clinical review.</p><div className={styles.actions}><Button as={Link} to="/role" variant="accent" size="lg">Get started <ArrowRight size={18} /></Button><a href="#how-it-works" className={styles.textLink}>How it works</a></div><div className={styles.note}>Screening support for clinical professionals. Not a standalone diagnosis.</div></div><div className={styles.heroPanel}><div className={styles.panelTop}><span>Participant task</span><strong>Hindi · हिन्दी</strong></div><div className={styles.picture}><PictureStimulus /></div><div className={styles.panelBottom}><div><span>Task</span><strong>Picture description</strong></div><div><span>Recording</span><strong>Voice response</strong></div></div></div></div></div></section>
        <section id="how-it-works" className={styles.section}><div className="container"><div className={styles.sectionIntro}><p className={styles.eyebrow}>The assessment</p><h2>One clear task. Structured review.</h2></div><div className={styles.steps}>{[['01', 'Choose language', 'The participant selects the language they will speak.'], ['02', 'Describe a picture', 'A standardized visual prompt keeps the task consistent.'], ['03', 'Record speech', 'Voice is captured in the browser with replay and re-record controls.'], ['04', 'Review change', 'Clinicians can compare speech, language and task indicators over time.']].map(([n, t, d]) => <div className={styles.step} key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
        <section className={styles.darkSection}><div className="container"><div className={styles.split}><div><p className={styles.eyebrowLight}>For older adults</p><h2>A quieter assessment experience.</h2><p>Large text, clear actions, fewer choices and straightforward instructions reduce unnecessary cognitive load.</p></div><div className={styles.featureList}>{['Large, readable controls', 'Optional spoken instructions', 'Real browser voice recording', 'No diagnostic result shown to participants'].map(x => <div key={x}><Check size={18} /><span>{x}</span></div>)}</div></div></div></section>
        <section className={styles.section}><div className="container"><div className={styles.sectionIntro}><p className={styles.eyebrow}>Languages</p><h2>Language stays part of the assessment.</h2><p>Memora keeps the participant's chosen language visible through the assessment workflow.</p></div><div className={styles.langGrid}>{languages.map(([a, b]) => <div className={styles.lang} key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div></section>
        <section className={styles.reportSection}><div className="container"><div className={styles.reportGrid}><div><p className={styles.eyebrow}>Clinical review</p><h2>From one recording to a longitudinal record.</h2><p>Review assessment quality, speech characteristics, language patterns, task performance, transcripts and descriptive change over time.</p><Button as={Link} to="/role" variant="secondary" size="lg">Open Memora <ArrowRight size={18} /></Button></div><div className={styles.report}><div className={styles.reportHeader}><FileText size={18} /><span>Clinical assessment report</span></div><div className={styles.reportRows}><div><span>Assessment quality</span><strong>Good</strong></div><div><span>Speech rate</span><strong>76 WPM</strong></div><div><span>Concept coverage</span><strong>7 / 10</strong></div><div><span>Review status</span><strong>Recommended</strong></div></div><div className={styles.reportFooter}><ShieldCheck size={16} /> Screening support only</div></div></div></div></section>
    </div>
}
